// <auto-generated />
using System;
using BlazorApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321151236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualPace")
                        .HasColumnType("REAL");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlannedDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlannedHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedPace")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("EnduranceLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");

                    b.HasDiscriminator<string>("ExerciseType").HasValue("Exercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrequencyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("RecurrenceRules");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("ScheduledWorkouts");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.SetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("SetLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinuteWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("TemplateGroups");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetPace")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("REAL");

                    b.Property<int?>("TemplateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateGroupId");

                    b.HasIndex("WorkoutTemplateId", "Position");

                    b.ToTable("TemplateItems");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduledWorkoutId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledWorkoutId")
                        .IsUnique();

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceExercise", b =>
                {
                    b.HasBaseType("BlazorApp2.Data.Entities.Exercise");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Endurance");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.StrengthExercise", b =>
                {
                    b.HasBaseType("BlazorApp2.Data.Entities.Exercise");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Strength");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("EnduranceLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.RecurrenceRule", "RecurrenceRule")
                        .WithMany("ScheduledWorkouts")
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecurrenceRule");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.SetLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("SetLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Groups")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateItem", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.TemplateGroup", "TemplateGroup")
                        .WithMany("Items")
                        .HasForeignKey("TemplateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Items")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TemplateGroup");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.ScheduledWorkout", "ScheduledWorkout")
                        .WithOne("WorkoutLog")
                        .HasForeignKey("BlazorApp2.Data.Entities.WorkoutLog", "ScheduledWorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduledWorkout");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.Navigation("ScheduledWorkouts");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.Navigation("EnduranceLogs");

                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
