// <auto-generated />
using System;
using BlazorApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321185044_AddTemplateTags")]
    partial class AddTemplateTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualPace")
                        .HasColumnType("REAL");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlannedDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlannedHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedPace")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("EnduranceLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");

                    b.HasDiscriminator<string>("ExerciseType").HasValue("Exercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrequencyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("RecurrenceRules");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("ScheduledWorkouts");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.SetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PlannedWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("SetLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinuteWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("TemplateGroups");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetDistance")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetHeartRateZone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetPace")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("REAL");

                    b.Property<int?>("TemplateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateGroupId");

                    b.HasIndex("WorkoutTemplateId", "Position");

                    b.ToTable("TemplateItems");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduledWorkoutId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledWorkoutId")
                        .IsUnique();

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceExercise", b =>
                {
                    b.HasBaseType("BlazorApp2.Data.Entities.Exercise");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Endurance");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conversational pace. You should be able to hold a full conversation. Keep heart rate in Zone 2.",
                            Name = "Easy Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortably hard pace you could sustain for about an hour. Breathing is labored but controlled. Zone 3-4.",
                            Name = "Tempo Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Alternate between hard efforts and recovery jogs. Work intervals at Zone 4-5. Recovery intervals at easy pace.",
                            Name = "Interval Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extended duration at easy to moderate pace. Build aerobic base and mental endurance. Longest run of the week.",
                            Name = "Long Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unstructured speed play. Vary pace throughout the run based on feel. Mix fast bursts with easy recovery periods.",
                            Name = "Fartlek Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Short all-out sprints up a steep hill. Walk or jog back down for recovery. Builds power and running economy.",
                            Name = "Hill Sprints",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Very easy pace, shorter duration. Promotes blood flow for recovery. Should feel effortless. Zone 1-2.",
                            Name = "Recovery Run",
                            ActivityType = 0
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low intensity cycling at conversational pace. Steady cadence of 80-90 RPM. Zone 2 effort for aerobic base building.",
                            Name = "Easy Ride",
                            ActivityType = 1
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sustained effort at threshold pace. Breathing is heavy but sustainable. Maintain steady power output in Zone 3-4.",
                            Name = "Tempo Ride",
                            ActivityType = 1
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-intensity intervals with recovery periods. Work intervals at Zone 4-5 power. Recovery at easy spinning.",
                            Name = "Interval Ride",
                            ActivityType = 1
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extended duration ride at moderate pace. Build endurance and fat adaptation. Longest ride of the week.",
                            Name = "Long Ride",
                            ActivityType = 1
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focus on sustained climbing efforts. Lower cadence, higher resistance. Builds leg strength and climbing fitness.",
                            Name = "Hill Climb Ride",
                            ActivityType = 1
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purposeful walking at an elevated pace. Arm swing engaged, stride slightly longer than normal. Low-impact active recovery.",
                            Name = "Brisk Walk",
                            ActivityType = 4
                        });
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.StrengthExercise", b =>
                {
                    b.HasBaseType("BlazorApp2.Data.Entities.Exercise");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Strength");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hang from bar with overhand grip shoulder-width apart. Pull until chin clears bar. Control the descent.",
                            Name = "Pull-Up",
                            Equipment = 2,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hang from bar with underhand grip shoulder-width apart. Pull until chin clears bar. Emphasizes biceps more than pull-up.",
                            Name = "Chin-Up",
                            Equipment = 2,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perform pull-up with added weight via belt or vest. Maintain strict form without kipping.",
                            Name = "Weighted Pull-Up",
                            Equipment = 2,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hang beneath a low bar with feet on ground. Pull chest to bar keeping body rigid. Scale by adjusting body angle.",
                            Name = "Inverted Row",
                            Equipment = 2,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One hand and knee on bench, row dumbbell to hip. Keep elbow close to body. Squeeze shoulder blade at top.",
                            Name = "Dumbbell Row",
                            Equipment = 1,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lie across bench with single dumbbell held overhead. Lower behind head with slight elbow bend. Engage lats to return.",
                            Name = "Dumbbell Pullover",
                            Equipment = 1,
                            MuscleGroup = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands shoulder-width apart, body in plank. Lower chest to floor keeping elbows at 45 degrees. Push back up fully.",
                            Name = "Push-Up",
                            Equipment = 2,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "On parallel bars, lean forward slightly for chest emphasis. Lower until shoulders are below elbows. Add weight via belt.",
                            Name = "Weighted Dip",
                            Equipment = 2,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands together forming diamond shape under chest. Lower and push up. Emphasizes inner chest and triceps.",
                            Name = "Diamond Push-Up",
                            Equipment = 2,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lie flat on bench, press dumbbells from chest level to full extension. Allows greater range of motion than barbell.",
                            Name = "Dumbbell Bench Press",
                            Equipment = 1,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lie flat on bench with dumbbells extended above chest. Lower with slight elbow bend in arc motion. Squeeze chest to return.",
                            Name = "Dumbbell Fly",
                            Equipment = 1,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Place feet on elevated surface, hands on floor. Perform push-up targeting upper chest. Higher surface increases difficulty.",
                            Name = "Incline Push-Up (Feet Elevated)",
                            Equipment = 2,
                            MuscleGroup = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start in downward dog position with hips high. Bend elbows to lower head toward floor. Press back up. Mimics overhead press.",
                            Name = "Pike Push-Up",
                            Equipment = 2,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand or sit with dumbbells at shoulder height. Press overhead to full lockout. Control the descent back to shoulders.",
                            Name = "Dumbbell Overhead Press",
                            Equipment = 1,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand with dumbbells at sides. Raise arms laterally to shoulder height with slight elbow bend. Lower with control.",
                            Name = "Lateral Raise",
                            Equipment = 1,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand with dumbbells in front of thighs. Raise one or both arms forward to shoulder height. Lower slowly.",
                            Name = "Dumbbell Front Raise",
                            Equipment = 1,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anchor band at face height. Pull toward face with elbows high, externally rotating at end. Targets rear delts and rotator cuff.",
                            Name = "Face Pull (Band)",
                            Equipment = 5,
                            MuscleGroup = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand shoulder-width apart. Sit back and down keeping chest up and knees tracking over toes. Descend to parallel or below.",
                            Name = "Bodyweight Squat",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rear foot elevated on bench. Lower front knee to 90 degrees keeping torso upright. Drive through front heel to stand.",
                            Name = "Bulgarian Split Squat",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand on one leg, extend other leg forward. Squat down to full depth on single leg. Requires balance and mobility.",
                            Name = "Pistol Squat",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hold kettlebell at chest level with both hands. Squat to parallel or below keeping elbows inside knees. Stand tall at top.",
                            Name = "Goblet Squat",
                            Equipment = 6,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hold dumbbells in front of thighs. Hinge at hips pushing them back, slight knee bend. Lower until hamstring stretch, drive hips forward.",
                            Name = "Romanian Deadlift (Dumbbell)",
                            Equipment = 1,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Step forward into split stance. Lower back knee toward floor. Push through front heel to return. Alternate legs.",
                            Name = "Lunge",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand on edge of step with heels hanging off. Rise onto toes as high as possible. Lower below platform level for full stretch.",
                            Name = "Calf Raise",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Step onto a sturdy elevated surface leading with one foot. Drive through heel to stand fully. Step down with control.",
                            Name = "Step-Up",
                            Equipment = 2,
                            MuscleGroup = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand with dumbbells at sides, palms forward. Curl to shoulders keeping elbows pinned to sides. Lower with control.",
                            Name = "Dumbbell Curl",
                            Equipment = 1,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand with dumbbells at sides, palms facing each other. Curl to shoulders maintaining neutral grip. Targets brachialis.",
                            Name = "Hammer Curl",
                            Equipment = 1,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "On parallel bars or bench edge, lower body by bending elbows to 90 degrees. Keep torso upright for tricep emphasis. Press up.",
                            Name = "Tricep Dip",
                            Equipment = 2,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hold single dumbbell overhead with both hands. Lower behind head by bending elbows. Extend back to lockout. Keep elbows close.",
                            Name = "Overhead Tricep Extension",
                            Equipment = 1,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sit on bench, brace elbow against inner thigh. Curl dumbbell to shoulder. Isolates the bicep with strict form.",
                            Name = "Concentration Curl",
                            Equipment = 1,
                            MuscleGroup = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Forearms and toes on floor, body in straight line. Brace core and hold position. Avoid sagging hips or piking up.",
                            Name = "Plank",
                            Equipment = 2,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hang from pull-up bar with straight arms. Raise legs to parallel or higher. Lower with control, avoid swinging.",
                            Name = "Hanging Leg Raise",
                            Equipment = 2,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kneel with ab wheel in front. Roll forward extending body as far as possible. Use core to pull back to start position.",
                            Name = "Ab Wheel Rollout",
                            Equipment = 7,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sit with knees bent and feet off floor. Lean back slightly and rotate torso side to side. Add weight for more resistance.",
                            Name = "Russian Twist",
                            Equipment = 2,
                            MuscleGroup = 5
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "From standing, drop to push-up position, perform push-up, jump feet to hands, explode upward. Full body conditioning movement.",
                            Name = "Burpee",
                            Equipment = 2,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lie on floor holding kettlebell overhead. Stand up through a series of positions while keeping weight locked out. Reverse to return.",
                            Name = "Turkish Get-Up",
                            Equipment = 6,
                            MuscleGroup = 6
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hinge at hips with kettlebell between legs. Drive hips forward explosively to swing weight to chest height. Control the backswing.",
                            Name = "Kettlebell Swing",
                            Equipment = 6,
                            MuscleGroup = 6
                        });
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.EnduranceLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("EnduranceLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.RecurrenceRule", "RecurrenceRule")
                        .WithMany("ScheduledWorkouts")
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecurrenceRule");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.SetLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("SetLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Groups")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateItem", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.Entities.TemplateGroup", "TemplateGroup")
                        .WithMany("Items")
                        .HasForeignKey("TemplateGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorApp2.Data.Entities.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Items")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TemplateGroup");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.HasOne("BlazorApp2.Data.Entities.ScheduledWorkout", "ScheduledWorkout")
                        .WithOne("WorkoutLog")
                        .HasForeignKey("BlazorApp2.Data.Entities.WorkoutLog", "ScheduledWorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduledWorkout");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.RecurrenceRule", b =>
                {
                    b.Navigation("ScheduledWorkouts");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.ScheduledWorkout", b =>
                {
                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.TemplateGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutLog", b =>
                {
                    b.Navigation("EnduranceLogs");

                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("BlazorApp2.Data.Entities.WorkoutTemplate", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
